#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Management
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RMS")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public DataDataContext() : 
				base(global::Restaurant_Management.Properties.Settings.Default.RMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _e_name;
		
		private string _e_email;
		
		private string _e_address;
		
		private System.Nullable<decimal> _e_salary;
		
		private string _e_role;
		
		private string _e_joining_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void One_nameChanging(string value);
    partial void One_nameChanged();
    partial void One_emailChanging(string value);
    partial void One_emailChanged();
    partial void One_addressChanging(string value);
    partial void One_addressChanged();
    partial void One_salaryChanging(System.Nullable<decimal> value);
    partial void One_salaryChanged();
    partial void One_roleChanging(string value);
    partial void One_roleChanged();
    partial void One_joining_dateChanging(string value);
    partial void One_joining_dateChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_name", DbType="VarChar(50)")]
		public string e_name
		{
			get
			{
				return this._e_name;
			}
			set
			{
				if ((this._e_name != value))
				{
					this.One_nameChanging(value);
					this.SendPropertyChanging();
					this._e_name = value;
					this.SendPropertyChanged("e_name");
					this.One_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_email", DbType="VarChar(50)")]
		public string e_email
		{
			get
			{
				return this._e_email;
			}
			set
			{
				if ((this._e_email != value))
				{
					this.One_emailChanging(value);
					this.SendPropertyChanging();
					this._e_email = value;
					this.SendPropertyChanged("e_email");
					this.One_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_address", DbType="VarChar(50)")]
		public string e_address
		{
			get
			{
				return this._e_address;
			}
			set
			{
				if ((this._e_address != value))
				{
					this.One_addressChanging(value);
					this.SendPropertyChanging();
					this._e_address = value;
					this.SendPropertyChanged("e_address");
					this.One_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_salary", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> e_salary
		{
			get
			{
				return this._e_salary;
			}
			set
			{
				if ((this._e_salary != value))
				{
					this.One_salaryChanging(value);
					this.SendPropertyChanging();
					this._e_salary = value;
					this.SendPropertyChanged("e_salary");
					this.One_salaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_role", DbType="VarChar(50)")]
		public string e_role
		{
			get
			{
				return this._e_role;
			}
			set
			{
				if ((this._e_role != value))
				{
					this.One_roleChanging(value);
					this.SendPropertyChanging();
					this._e_role = value;
					this.SendPropertyChanged("e_role");
					this.One_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_joining_date", DbType="VarChar(50)")]
		public string e_joining_date
		{
			get
			{
				return this._e_joining_date;
			}
			set
			{
				if ((this._e_joining_date != value))
				{
					this.One_joining_dateChanging(value);
					this.SendPropertyChanging();
					this._e_joining_date = value;
					this.SendPropertyChanged("e_joining_date");
					this.One_joining_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
